### ISSUE TITLE
Cannot find module 'templates.js'

### ISSUE THREAD

**Issue by anjeve** [NicolasSiver/nodebb-widget-ns-stats#6]
I'm getting this error after installing the widget and restarting my nodebb (v1.8.2):

```
2018-04-09T05:53:22.944Z [4968] - ^[[31merror^[[39m: Error: Cannot find module 'templates.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at /home/nodebb/twinpeaks/node_modules/nodebb-widget-ns-stats/widget/nodebb.js:43:27
    at Object.<anonymous> (/home/nodebb/.../node_modules/nodebb-widget-ns-stats/widget/nodebb.js:45:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /home/nodebb/twinpeaks/node_modules/nodebb-widget-ns-stats/widget/job.js:7:18
    at Object.<anonymous> (/home/nodebb/.../node_modules/nodebb-widget-ns-stats/widget/job.js:65:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
2018-04-09T05:53:22.945Z [4968] - ^[[33mwarn^[[39m: [plugins] Unable to parse library for: nodebb-widget-ns-stats
```
Any idea how to fix this?

**Comment by NicolasSiver** [comment]
Hello,

Looking at the error. Module responsible for the templates was moved, renamed or removed.
It means that plugin is not compatible with NodeBB `1.8.x`.
Plugin compatibility should be changed because now it says that every future version 1.9, 1.10, even 1.8 will work without any issue with a plugin, which is not true.

**Comment by NicolasSiver** [comment]
Try latest version `v2`. It should work well with latest NodeBB v1.8.x
